### ISSUE TITLE
Unpurchased Chocolate Egg causes HUGE Cookie gain.

### ISSUE THREAD

**Issue by AlfadorVII** [Anahkiasen/cookie-monster#52]
I found the Chocolate Egg upgrade, and decided not to buy it until I was ready to reset, as that's the best time to use it.

When I left Cookie Clicker running for several hours and came back, my total Cookies had shot up to well over a Decillion, buying the Chocolate Egg stops the madness, but sadly too late for my game.

**Comment by progheal** [comment]
I have the same problem here. (v1.046.01)
The following is my observation and guess; I didn't read through the source code of Cookie Monster so correct me if I'm wrong.
When Cookie Monster try to calculate the benefit of a building or upgrade, it will actually buy it, see how much cps it gained, and then sell it. If the buy action have side effect (eg. gain an achievement like having 100 building, or in this case, buying Chocolate Egg gives you 5% of your bank), that side effect will not be reversed. I think this is the root cause.
This is also why the achievements like 100 building will unlock with one fewer building when you use Cookie Monster. A rather special case is the achievement 'Just Wrong' which is unlocked when you sell a grandma; if you haven't unlock this achievement, you will unlock it a little while after you load Cookie Monster.
Some mathematics gives that the bank cookie will double every 14~15 updates; the update period is 10 sec, which means the bank cookie will double about every two and a half minutes. So several hours will definitely mess up the whole game...

**Comment by Qhorin** [comment]
Good work, @progheal . Thanks for determining the cause. I'll see if I can find a way to fix that.

**Comment by Qhorin** [comment]
I've submitted a fix for the Chocolate Egg issue. I will open a new issue with the Achievement issues @progheal described. The two issues are similar, in that, they both are caused by the simulateBuy, but the solutions are different.
